In [1]:
import pandas as pd

In [ ]:
Result= {
    "Names" : ["Arhan", "Raahim", "Hamza", "Meesum"],
    "Rollno" : [441, 442, 443, 444],
    "Maths" : [45, 65, 55, 64],
    "English" : [40, 50, 30, 60],
    "Science" : [20, 50, 40, 60]
}
print(Result)
a = pd.DataFrame(Result)
a

{'Names': ['Arhan', 'Raahim', 'Hamza', 'Meesum'], 'Rollno': [441, 442, 443, 444], 'Maths': [45, 65, 55, 64], 'English': [40, 50, 30, 60], 'Science': [20, 50, 40, 60]}

           Rollno      Maths    English    Science
count    4.000000   4.000000   4.000000   4.000000
mean   442.500000  57.250000  45.000000  42.500000
std      1.290994   9.322911  12.909944  17.078251
min    441.000000  45.000000  30.000000  20.000000
25%    441.750000  52.500000  37.500000  35.000000
50%    442.500000  59.500000  45.000000  45.000000
75%    443.250000  64.250000  52.500000  52.500000
max    444.000000  65.000000  60.000000  60.000000

In [7]:
a.shape

(4, 5)

In [9]:
a.head(2)

    Names  Rollno  Maths  English  Science
0   Arhan     441     45       40       20
1  Raahim     442     65       50       50

In [10]:
a.tail(3)

    Names  Rollno  Maths  English  Science
1  Raahim     442     65       50       50
2   Hamza     443     55       30       40
3  Meesum     444     64       60       60

In [11]:
a.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Names    4 non-null      str
 1   Rollno   4 non-null      int64
 2   Maths    4 non-null      int64
 3   English  4 non-null      int64
 4   Science  4 non-null      int64
dtypes: int64(4), str(1)
memory usage: 292.0 bytes

In [12]:
a.describe()

           Rollno      Maths    English    Science
count    4.000000   4.000000   4.000000   4.000000
mean   442.500000  57.250000  45.000000  42.500000
std      1.290994   9.322911  12.909944  17.078251
min    441.000000  45.000000  30.000000  20.000000
25%    441.750000  52.500000  37.500000  35.000000
50%    442.500000  59.500000  45.000000  45.000000
75%    443.250000  64.250000  52.500000  52.500000
max    444.000000  65.000000  60.000000  60.000000